# Generated by Django 5.2.6 on 2025-09-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0002_insert_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
